services:
  - type: web
    name: pr-review-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"

  - type: web
    name: pr-review-frontend
    env: static
    buildCommand: "cd frontend && npm ci && npm run build"
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://pr-review-backend.onrender.com
